2014-09-15 02:04:55 Error: [MissingTableException] Table pessoa_modulos for model PessoaModulo was not found in datasource default.
Exception Attributes: array (
  'table' => 'pessoa_modulos',
  'class' => 'PessoaModulo',
  'ds' => 'default',
)
Request URL: /instapro/
Stack Trace:
#0 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3499): Model->setSource('pessoa_modulos')
#1 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1447): Model->schema()
#3 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1434): Model->hasField('title', false)
#4 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(880): Model->hasField(Array)
#5 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3070): Model->__get('displayField')
#6 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2935): Model->_findList('before', Array)
#7 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2870): Model->buildQuery('list', Array)
#8 D:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array)
#9 [internal function]: PessoasController->login()
#10 D:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#11 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#12 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#13 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-09-15 02:06:28 Error: [MissingTableException] Table pessoa_modulos for model PessoaModulo was not found in datasource default.
Exception Attributes: array (
  'table' => 'pessoa_modulos',
  'class' => 'PessoaModulo',
  'ds' => 'default',
)
Request URL: /instapro/
Stack Trace:
#0 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3499): Model->setSource('pessoa_modulos')
#1 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1447): Model->schema()
#3 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1434): Model->hasField('title', false)
#4 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(880): Model->hasField(Array)
#5 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3070): Model->__get('displayField')
#6 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2935): Model->_findList('before', Array)
#7 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2870): Model->buildQuery('list', Array)
#8 D:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array)
#9 [internal function]: PessoasController->login()
#10 D:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#11 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#12 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#13 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-09-15 02:06:38 Error: [MissingTableException] Table pessoa_modulos for model PessoaModulo was not found in datasource default.
Exception Attributes: array (
  'table' => 'pessoa_modulos',
  'class' => 'PessoaModulo',
  'ds' => 'default',
)
Request URL: /instapro/
Stack Trace:
#0 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3499): Model->setSource('pessoa_modulos')
#1 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1447): Model->schema()
#3 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1434): Model->hasField('title', false)
#4 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(880): Model->hasField(Array)
#5 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3070): Model->__get('displayField')
#6 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2935): Model->_findList('before', Array)
#7 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2870): Model->buildQuery('list', Array)
#8 D:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array)
#9 [internal function]: PessoasController->login()
#10 D:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#11 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#12 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#13 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-09-15 03:19:45 Error: [MissingControllerException] Controller class Favicon.pngController could not be found.
Exception Attributes: array (
  'class' => 'Favicon.pngController',
  'plugin' => NULL,
)
Request URL: /instapro/favicon.png
Stack Trace:
#0 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-15 03:19:45 Error: [MissingControllerException] Controller class Favicon.pngController could not be found.
Exception Attributes: array (
  'class' => 'Favicon.pngController',
  'plugin' => NULL,
)
Request URL: /instapro/favicon.png
Stack Trace:
#0 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-15 03:20:07 Error: [MissingTableException] Table pessoa_modulos for model PessoaModulo was not found in datasource default.
Exception Attributes: array (
  'table' => 'pessoa_modulos',
  'class' => 'PessoaModulo',
  'ds' => 'default',
)
Request URL: /instapro/
Stack Trace:
#0 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3499): Model->setSource('pessoa_modulos')
#1 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1447): Model->schema()
#3 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1434): Model->hasField('title', false)
#4 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(880): Model->hasField(Array)
#5 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3070): Model->__get('displayField')
#6 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2935): Model->_findList('before', Array)
#7 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2870): Model->buildQuery('list', Array)
#8 D:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array)
#9 [internal function]: PessoasController->login()
#10 D:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#11 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#12 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#13 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-09-15 03:20:33 Error: [MissingTableException] Table pessoa_modulos for model PessoaModulo was not found in datasource default.
Exception Attributes: array (
  'table' => 'pessoa_modulos',
  'class' => 'PessoaModulo',
  'ds' => 'default',
)
Request URL: /instapro/
Stack Trace:
#0 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3499): Model->setSource('pessoa_modulos')
#1 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1447): Model->schema()
#3 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1434): Model->hasField('title', false)
#4 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(880): Model->hasField(Array)
#5 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3070): Model->__get('displayField')
#6 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2935): Model->_findList('before', Array)
#7 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2870): Model->buildQuery('list', Array)
#8 D:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array)
#9 [internal function]: PessoasController->login()
#10 D:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#11 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#12 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#13 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-09-15 03:20:39 Error: [MissingTableException] Table pessoa_modulos for model PessoaModulo was not found in datasource default.
Exception Attributes: array (
  'table' => 'pessoa_modulos',
  'class' => 'PessoaModulo',
  'ds' => 'default',
)
Request URL: /instapro/
Stack Trace:
#0 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3499): Model->setSource('pessoa_modulos')
#1 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1447): Model->schema()
#3 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1434): Model->hasField('title', false)
#4 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(880): Model->hasField(Array)
#5 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3070): Model->__get('displayField')
#6 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2935): Model->_findList('before', Array)
#7 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2870): Model->buildQuery('list', Array)
#8 D:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array)
#9 [internal function]: PessoasController->login()
#10 D:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#11 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#12 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#13 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-09-15 03:20:49 Error: [MissingTableException] Table pessoa_modulos for model PessoaModulo was not found in datasource default.
Exception Attributes: array (
  'table' => 'pessoa_modulos',
  'class' => 'PessoaModulo',
  'ds' => 'default',
)
Request URL: /instapro/
Stack Trace:
#0 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3499): Model->setSource('pessoa_modulos')
#1 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1447): Model->schema()
#3 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1434): Model->hasField('title', false)
#4 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(880): Model->hasField(Array)
#5 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3070): Model->__get('displayField')
#6 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2935): Model->_findList('before', Array)
#7 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2870): Model->buildQuery('list', Array)
#8 D:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array)
#9 [internal function]: PessoasController->login()
#10 D:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#11 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#12 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#13 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-09-15 03:20:55 Error: [MissingControllerException] Controller class Favicon.pngController could not be found.
Exception Attributes: array (
  'class' => 'Favicon.pngController',
  'plugin' => NULL,
)
Request URL: /instapro/favicon.png
Stack Trace:
#0 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-15 03:21:08 Error: [MissingTableException] Table pessoa_modulos for model PessoaModulo was not found in datasource default.
Exception Attributes: array (
  'table' => 'pessoa_modulos',
  'class' => 'PessoaModulo',
  'ds' => 'default',
)
Request URL: /instapro/
Stack Trace:
#0 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3499): Model->setSource('pessoa_modulos')
#1 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1447): Model->schema()
#3 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1434): Model->hasField('title', false)
#4 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(880): Model->hasField(Array)
#5 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3070): Model->__get('displayField')
#6 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2935): Model->_findList('before', Array)
#7 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2870): Model->buildQuery('list', Array)
#8 D:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array)
#9 [internal function]: PessoasController->login()
#10 D:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#11 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#12 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#13 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-09-16 03:39:11 Error: [MissingTableException] Table pessoa_modulos for model PessoaModulo was not found in datasource default.
Exception Attributes: array (
  'table' => 'pessoa_modulos',
  'class' => 'PessoaModulo',
  'ds' => 'default',
)
Request URL: /instapro/
Stack Trace:
#0 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3499): Model->setSource('pessoa_modulos')
#1 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1447): Model->schema()
#3 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1434): Model->hasField('title', false)
#4 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(880): Model->hasField(Array)
#5 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3070): Model->__get('displayField')
#6 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2935): Model->_findList('before', Array)
#7 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2870): Model->buildQuery('list', Array)
#8 D:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array)
#9 [internal function]: PessoasController->login()
#10 D:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#11 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#12 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#13 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
2014-09-20 22:44:14 Error: [MissingTableException] Table pessoa_modulos for model PessoaModulo was not found in datasource default.
Exception Attributes: array (
  'table' => 'pessoa_modulos',
  'class' => 'PessoaModulo',
  'ds' => 'default',
)
Request URL: /instapro/
Stack Trace:
<<<<<<< HEAD
#0 D:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 D:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('INSERT INTO `in...', Array)
#2 D:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(1004): DboSource->execute('INSERT INTO `in...')
#3 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1832): DboSource->create(Object(Pessoas), Array, Array)
#4 D:\xampp\htdocs\instapro\app\Controller\PessoasController.php(39): Model->save(Array)
#5 [internal function]: PessoasController->adicionar()
#6 D:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#7 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#8 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#9 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-08-27 05:03:21 Error: [MissingControllerException] Controller class Favicon.pngController could not be found.
Exception Attributes: array (
  'class' => 'Favicon.pngController',
  'plugin' => NULL,
)
Request URL: /instapro/favicon.png
Stack Trace:
#0 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-27 05:03:21 Error: [MissingControllerException] Controller class Favicon.pngController could not be found.
Exception Attributes: array (
  'class' => 'Favicon.pngController',
  'plugin' => NULL,
)
Request URL: /instapro/favicon.png
Stack Trace:
#0 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-27 17:54:03 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\instapro\app\Controller\PessoasController.php, line 179]
2014-08-27 17:54:03 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 179)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 179, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 179, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
=======
#0 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3499): Model->setSource('pessoa_modulos')
#1 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1355): Model->getDataSource()
#2 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1447): Model->schema()
#3 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(1434): Model->hasField('title', false)
#4 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(880): Model->hasField(Array)
#5 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(3070): Model->__get('displayField')
#6 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2935): Model->_findList('before', Array)
#7 D:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2870): Model->buildQuery('list', Array)
#8 D:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array)
#9 [internal function]: PessoasController->login()
#10 D:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#11 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#12 D:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#13 D:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#14 {main}
>>>>>>> 95932894aee4940efca7a4570e5b435c74e7e0e2
2014-09-20 23:02:11 Error: [MissingControllerException] Controller class Favicon.pngController could not be found.
Exception Attributes: array (
  'class' => 'Favicon.pngController',
  'plugin' => NULL,
)
Request URL: /instapro/favicon.png
Stack Trace:
#0 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-20 23:02:12 Error: [MissingControllerException] Controller class Favicon.pngController could not be found.
Exception Attributes: array (
  'class' => 'Favicon.pngController',
  'plugin' => NULL,
)
Request URL: /instapro/favicon.png
Stack Trace:
#0 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-20 23:02:26 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'PessoaModulo.id' in 'field list'
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `PessoaM...', Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(665): DboSource->execute('SELECT `PessoaM...', Array, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `PessoaM...', false)
#4 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2903): DboSource->read(Object(PessoaModulo), Array)
#5 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2875): Model->_readDataSource('list', Array)
#6 C:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array)
#7 [internal function]: PessoasController->login()
#8 C:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#9 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-09-23 04:46:48 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\instapro\app\Controller\PessoasController.php, line 152]
2014-09-23 04:46:48 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 152)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 152, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 152, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-23 04:48:44 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'PessoaModulo.id' in 'field list'
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `PessoaM...', Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(665): DboSource->execute('SELECT `PessoaM...', Array, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `PessoaM...', false)
#4 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2903): DboSource->read(Object(PessoaModulo), Array)
#5 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2875): Model->_readDataSource('list', Array)
#6 C:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array)
#7 [internal function]: PessoasController->login()
#8 C:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#9 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-09-23 04:49:41 Error: Fatal Error (4): syntax error, unexpected T_ARRAY, expecting ')' in [C:\xampp\htdocs\instapro\app\Controller\PessoasController.php, line 152]
2014-09-23 04:49:41 Error: [FatalErrorException] syntax error, unexpected T_ARRAY, expecting ')'
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 152)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 152, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 152, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-23 04:50:19 Error: Fatal Error (4): syntax error, unexpected T_ARRAY in [C:\xampp\htdocs\instapro\app\Controller\PessoasController.php, line 152]
2014-09-23 04:50:19 Error: [FatalErrorException] syntax error, unexpected T_ARRAY
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 152)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 152, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 152, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-23 04:50:46 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\instapro\app\Controller\PessoasController.php, line 152]
2014-09-23 04:50:46 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 152)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 152, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 152, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-23 04:52:16 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'PessoaModulo.id' in 'field list'
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `PessoaM...', Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(665): DboSource->execute('SELECT `PessoaM...', Array, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `PessoaM...', false)
#4 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2903): DboSource->read(Object(PessoaModulo), Array)
#5 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2875): Model->_readDataSource('list', Array)
#6 C:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array, Array)
#7 [internal function]: PessoasController->login()
#8 C:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#9 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-09-23 04:54:17 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'PessoaModulo.id' in 'field list'
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `PessoaM...', Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(665): DboSource->execute('SELECT `PessoaM...', Array, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `PessoaM...', false)
#4 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2903): DboSource->read(Object(PessoaModulo), Array)
#5 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2875): Model->_readDataSource('list', Array)
#6 C:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array, Array)
#7 [internal function]: PessoasController->login()
#8 C:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#9 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-09-23 04:54:42 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'PessoaModulo.id' in 'field list'
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `PessoaM...', Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(665): DboSource->execute('SELECT `PessoaM...', Array, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `PessoaM...', false)
#4 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2903): DboSource->read(Object(PessoaModulo), Array)
#5 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2875): Model->_readDataSource('list', Array)
#6 C:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array, Array)
#7 [internal function]: PessoasController->login()
#8 C:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#9 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-09-23 04:54:47 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'PessoaModulo.id' in 'field list'
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `PessoaM...', Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(665): DboSource->execute('SELECT `PessoaM...', Array, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `PessoaM...', false)
#4 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2903): DboSource->read(Object(PessoaModulo), Array)
#5 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2875): Model->_readDataSource('list', Array)
#6 C:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array, Array)
#7 [internal function]: PessoasController->login()
#8 C:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#9 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-09-23 04:55:44 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'PessoaModulo.idpessoa' in 'field list'
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `PessoaM...', Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(665): DboSource->execute('SELECT `PessoaM...', Array, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `PessoaM...', false)
#4 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2903): DboSource->read(Object(PessoaModulo), Array)
#5 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2875): Model->_readDataSource('list', Array)
#6 C:\xampp\htdocs\instapro\app\Controller\PessoasController.php(152): Model->find('list', Array, Array)
#7 [internal function]: PessoasController->login()
#8 C:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#9 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#10 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#11 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2014-09-25 04:19:12 Error: [MissingControllerException] Controller class Favicon.pngController could not be found.
Exception Attributes: array (
  'class' => 'Favicon.pngController',
  'plugin' => NULL,
)
Request URL: /instapro/favicon.png
Stack Trace:
#0 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-25 04:19:12 Error: [MissingControllerException] Controller class Favicon.pngController could not be found.
Exception Attributes: array (
  'class' => 'Favicon.pngController',
  'plugin' => NULL,
)
Request URL: /instapro/favicon.png
Stack Trace:
#0 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-28 23:51:30 Error: Fatal Error (4): syntax error, unexpected T_IF in [C:\xampp\htdocs\instapro\app\Controller\PessoasController.php, line 189]
2014-09-28 23:51:30 Error: [FatalErrorException] syntax error, unexpected T_IF
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 189)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 189, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 189, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-28 23:58:04 Error: Fatal Error (1): Function name must be a string in [C:\xampp\htdocs\instapro\app\View\Pessoas\editar.ctp, line 2]
2014-09-28 23:58:04 Error: [FatalErrorException] Function name must be a string
Request URL: /instapro/pessoas/editar/4
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Function name m...', 'C:\xampp\htdocs...', 2)
#1 [internal function]: ErrorHandler::handleError(1, 'Function name m...', 'C:\xampp\htdocs...', 2, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Function name m...', 'C:\xampp\htdocs...', 2, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-29 00:03:06 Error: Fatal Error (4): syntax error, unexpected '<' in [C:\xampp\htdocs\instapro\app\View\Pessoas\editar.ctp, line 2]
2014-09-29 00:03:06 Error: [FatalErrorException] syntax error, unexpected '<'
Request URL: /instapro/pessoas/editar/4
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 2)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 2, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 2, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-29 00:15:37 Error: Fatal Error (4): syntax error, unexpected T_VARIABLE, expecting '(' in [C:\xampp\htdocs\instapro\app\Controller\PessoasController.php, line 184]
2014-09-29 00:15:37 Error: [FatalErrorException] syntax error, unexpected T_VARIABLE, expecting '('
Request URL: /instapro/pessoas/editar/4
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 184)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 184, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 184, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-29 00:16:03 Error: Fatal Error (4): syntax error, unexpected T_STRING in [C:\xampp\htdocs\instapro\app\Controller\PessoasController.php, line 184]
2014-09-29 00:16:03 Error: [FatalErrorException] syntax error, unexpected T_STRING
Request URL: /instapro/pessoas/editar/4
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 184)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 184, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 184, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-29 00:18:25 Error: Fatal Error (1): Call to undefined function print_t() in [C:\xampp\htdocs\instapro\app\Controller\PessoasController.php, line 185]
2014-09-29 00:18:25 Error: [FatalErrorException] Call to undefined function print_t()
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 185)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 185, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\xampp\htdocs...', 185, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-29 00:47:28 Error: Fatal Error (4): syntax error, unexpected T_OBJECT_OPERATOR in [C:\xampp\htdocs\instapro\app\Controller\PessoasController.php, line 184]
2014-09-29 00:47:28 Error: [FatalErrorException] syntax error, unexpected T_OBJECT_OPERATOR
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 184)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 184, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 184, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-29 01:05:52 Error: Fatal Error (1): Call to undefined function array_count() in [C:\xampp\htdocs\instapro\app\Controller\PessoasController.php, line 201]
2014-09-29 01:05:52 Error: [FatalErrorException] Call to undefined function array_count()
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 201)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\xampp\htdocs...', 201, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\xampp\htdocs...', 201, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-29 01:08:04 Error: [PDOException] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'instapro.modulo' doesn't exist
Request URL: /instapro/
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(458): PDOStatement->execute(Array)
#1 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(424): DboSource->_execute('SELECT `Modulo`...', Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(665): DboSource->execute('SELECT `Modulo`...', Array, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `Modulo`...', false)
#4 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2903): DboSource->read(Object(PessoaModulo), Array)
#5 C:\xampp\htdocs\instapro\lib\Cake\Model\Model.php(2875): Model->_readDataSource('all', Array)
#6 C:\xampp\htdocs\instapro\app\Controller\PessoasController.php(200): Model->find('all', Array)
#7 C:\xampp\htdocs\instapro\app\Controller\PessoasController.php(156): PessoasController->registerSession(Array)
#8 [internal function]: PessoasController->login()
#9 C:\xampp\htdocs\instapro\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(PessoasController), Array)
#10 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#11 C:\xampp\htdocs\instapro\lib\Cake\Routing\Dispatcher.php(160): Dispatcher->_invoke(Object(PessoasController), Object(CakeRequest), Object(CakeResponse))
#12 C:\xampp\htdocs\instapro\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
2014-09-29 07:05:34 Error: Fatal Error (4): syntax error, unexpected $end in [C:\xampp\htdocs\instapro\app\View\Layouts\default.ctp, line 152]
2014-09-29 07:05:34 Error: [FatalErrorException] syntax error, unexpected $end
Request URL: /instapro/pessoas
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 152)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 152, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 152, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-29 07:07:04 Error: Fatal Error (4): syntax error, unexpected '}', expecting ',' or ';' in [C:\xampp\htdocs\instapro\app\View\Layouts\default.ctp, line 109]
2014-09-29 07:07:04 Error: [FatalErrorException] syntax error, unexpected '}', expecting ',' or ';'
Request URL: /instapro/pessoas
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 109)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 109, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 109, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-29 07:32:10 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\instapro\app\View\Layouts\default.ctp, line 105]
2014-09-29 07:32:10 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /instapro/pessoas
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 105)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 105, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 105, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-29 07:33:15 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\instapro\app\View\Layouts\default.ctp, line 105]
2014-09-29 07:33:15 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /instapro/pessoas
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 105)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\xampp\htdocs...', 105, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\xampp\htdocs...', 105, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-29 07:34:26 Error: Fatal Error (1): Call to a member function write() on a non-object in [C:\xampp\htdocs\instapro\app\View\Layouts\default.ctp, line 105]
2014-09-29 07:34:26 Error: [FatalErrorException] Call to a member function write() on a non-object
Request URL: /instapro/pessoas/editar/3
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 105)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 105, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 105, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-29 07:34:29 Error: Fatal Error (1): Call to a member function write() on a non-object in [C:\xampp\htdocs\instapro\app\View\Layouts\default.ctp, line 105]
2014-09-29 07:34:29 Error: [FatalErrorException] Call to a member function write() on a non-object
Request URL: /instapro/pessoas
Stack Trace:
#0 C:\xampp\htdocs\instapro\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 105)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\xampp\htdocs...', 105, Array)
#2 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(929): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\xampp\htdocs...', 105, Array)
#3 C:\xampp\htdocs\instapro\lib\Cake\Core\App.php(902): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
